### ISSUE TITLE
Issue When Compiled on Linux

### ISSUE THREAD

**Issue by Gibberditoslumber** [PouriaSFMs/Vs_FNaF_1_Full_Source#2]
try's to find a non exsistient so file

**Comment by McJonnycat** [comment]
what does it say on your terminal?

**Comment by Gibberditoslumber** [comment]
![image](https://user-images.githubusercontent.com/91945956/161276030-fbea57fa-3f44-4d23-b9b1-217ee150d2e3.png)

**Comment by McJonnycat** [comment]
that should work

**Comment by Gibberditoslumber** [comment]
thanks

**Comment by McJonnycat** [comment]
np bud

**Comment by Gibberditoslumber** [comment]
welp guest this isn't a problem any more

**Comment by McJonnycat** [comment]
do you want to close it?

**Comment by Gibberditoslumber** [comment]
yeah

**Comment by Gibberditoslumber** [comment]
it didn't work

**Comment by Gibberditoslumber** [comment]
https://user-images.githubusercontent.com/91945956/161276030-fbea57fa-3f44-4d23-b9b1-217ee150d2e3.png
IT STILL DIDN'T WORK

**Comment by McJonnycat** [comment]
ohh 
put if desktop instead of if windows

**Comment by McJonnycat** [comment]
so it can use the linc_luajit

**Comment by McJonnycat** [comment]
opps nvm

**Comment by Gibberditoslumber** [comment]
i fixed it myself

**Comment by McJonnycat** [comment]
how did you fixed it?

**Comment by Gibberditoslumber** [comment]
put the so file it was tring to find in the lib dictroy

**Comment by Gibberditoslumber** [comment]
the lib file was in linc_luajit
